version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app_coveragex
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todo_app_coveragex
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules  # Prevent node_modules conflict on host

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"   
    depends_on:
      - backend